[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "cython>=3.0a6",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=DarkNews"
testpaths = [
    "tests",
]

[tool.black]
line-length = 160